FROM balenalib/armv7hf-debian

ENTRYPOINT []

RUN install_packages darkice curl pulseaudio-utils sox shadow

RUN curl -k https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh --output wait-for-it.sh && chmod +x wait-for-it.sh && \
    chmod +x /start.sh
COPY pulse-client.conf /etc/pulse/client.conf

RUN useradd -ms /bin/bash darkice
COPY start.sh darkice.cfg ./
USER darkice

CMD ./start.sh
