version: "3.4"
services:

  ogn:
    image: rvantwisk/ogn:202110101256
    volumes:
      - ./Station.conf:/opt/Station.conf:ro
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb
    ports:
      - 50010:50010
      - 8080:8080
      - 8081:8081
