version: "3.4"
services:

  rtlsdr_dump1090:
    image: "rvantwisk/rtlsdr_dump1090"
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb
    volumes:
      - ./dump1090data:/dump1090data
      - dump1090html:/usr/share/dump1090-fa/html:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TERM=xterm
      - LONGITUDE=4.736318
      - LATITUDE=52.892658
      - CORRECTION=21
    ports:
      - 30001:30001
      - 30002:30002
      - 30003:30003
      - 30004:30004
      - 30005:30005
      - 30104:30104

  nginx:
    image: "arm32v7/nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mime.types:/mime.types:ro
      - dump1090html:/usr/share/dump1090-fa/html:ro
      - ./dump1090data:/dump1090data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"

  piaware:
    image: rvantwisk/flightaware
    restart: unless-stopped
    volumes:
      - ./piaware.conf:/etc/piaware.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30105:30105"
      - "30106:30106"

  adsbexchange-feed:
    image: 'marcelstoer/adsbexchange-feed:latest'
    restart: unless-stopped
    environment:
    - INPUT=rtlsdr_dump1090:30005
    container_name: adsbexchange-feed
    volumes:
      - /etc/localtime:/etc/localtime:ro

  adsbexchange-mlat:
    image: 'marcelstoer/adsbexchange-mlat:latest'
    restart: unless-stopped
    environment:
      - INPUT=rtlsdr_dump1090:30005
      - MLAT_RESULTS=rtlsdr_dump1090:30104
      # add the geo coordinates of your ADS-B reeiver
      - RECEIVER_LATITUDE=52.89267
      - RECEIVER_LONGITUDE=4.73628
      - RECEIVER_ALTITUDE=30
      # identify your receiver with something unique
      - RECEIVER_NAME=aeroclub
    container_name: adsbexchange-mlat
    volumes:
      - /etc/localtime:/etc/localtime:ro

  adsbhub:
    image: rvantwisk/adsbhub
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  fr24feed:
    image: rvantwisk/fr24feed
    restart: unless-stopped
    tty: true
    volumes:
      - ./fr24feed.ini:/etc/fr24feed/fr24feed.ini
      - ./fr24log:/var/log/fr24feed
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8754:8754"

  opensky:
    image: rvantwisk/opensky
    restart: unless-stopped
    volumes:
      - ./opensky-10-debconf.conf:/var/lib/openskyd/conf.d/10-debconf.conf:ro
      - ./opensky-05-serial.conf:/var/lib/openskyd/conf.d/05-serial.conf
      - /etc/localtime:/etc/localtime:ro

volumes:
  dump1090html:
